### ISSUE TITLE
Many of response types has type `unknown | sring | null` that doesn't make sense

### ISSUE THREAD

**Issue by visortelle** [cloudflare/cloudflare-typescript#1122]
Hi! The `unknown | string | null` is a useless type for library users because the `unknown` part makes everything else useless. 
It should be `string | null` instead.

https://github.com/search?q=repo%3Acloudflare%2Fcloudflare-typescript+%22unknown+%7C+string+%7C+null%22&type=code&p=2

<img width="726" alt="Screenshot 2024-07-05 at 3 47 00 PM" src="https://github.com/cloudflare/cloudflare-typescript/assets/9302460/0d1b1584-80aa-429a-9cab-ace8c8869907">

---
> By the way, there is no normal way to raise a GitHub issue in this repo. I used the URL substitution to create this one. I think contacting Cloudflare support is an overkill to resolve such issues.

<img width="1188" alt="Screenshot 2024-07-05 at 3 45 17 PM" src="https://github.com/cloudflare/cloudflare-typescript/assets/9302460/fca6e2e0-60c7-4a57-8b98-b8345078a2e6">

Thanks.

**Comment by jacobbednarz** [comment]
this is expected for now as some of the schemas are not yet complete and need work by the service teams to define what these response objects look like.

**Comment by visortelle** [comment]
@jacobbednarz Why close this issue? I think it's not so hard to fix it.

**Comment by visortelle** [comment]
@jacobbednarz I could submit a PR.

**Comment by jacobbednarz** [comment]
this is closed because:

1. it is not something that we need to address here but in the source schemas that these libraries are using the codegen the structures. 
2. the teams are already tracking this work internally and will prioritise it accordingly. as they fix the structures, it will automatically flow through to the libraries.
