### ISSUE TITLE
how to set env_vars

### ISSUE THREAD

**Issue by xcaptain** [cloudflare/cloudflare-typescript#1409]
https://github.com/cloudflare/cloudflare-typescript/blob/8bf5e89599793d44d6b8941795703129a362b510/tests/api-resources/pages/projects/projects.test.ts#L47

The api doc: https://developers.cloudflare.com/api/operations/pages-project-create-project

to specify env_vars, use:
```json
 "env_vars": {
    "property1": {
      "type": "plain_text",
      "value": "hello world"
    },
    "property2": {
      "type": "plain_text",
      "value": "hello world"
    }
  }
```

Don't know how to set 2 env variables using the typescript sdk

**Comment by jacobbednarz** [comment]
the test file you've linked to above is how to do it. the line you've highlighted is exactly what you need on a per environment basis.
