### ISSUE TITLE
Wrong action name used when creating page rules

### ISSUE THREAD

**Issue by coreycoto** [cloudflare/cloudflare-typescript#496]
When a Forwarding URL page rule is created via the Dashboard and then retrieved via the API then the action id is `forwarding_url`. The TypeScript SDK requires this value to be `forward_url`. However, when [``](https://developers.cloudflare.com/api/operations/page-rules-create-a-page-rule) is called with `forward_url` then the API returns an `HTTP 400` with a message `Unable to parse page rule`.

Change the SDK to use `forwarding_url` instead of `forward_url`.

https://github.com/cloudflare/cloudflare-typescript/blob/08057f19d0848dda00aeeb0d6d4af6bbe6c08205/src/resources/pagerules/pagerules.ts#L156

**Comment by jacobbednarz** [comment]
despite the confusing name, `forward_url` is different to `forwarding_url`. you'll want to use the latter when interacting with the API to get the desired effect you want here. 

it doesn't look like the types are being exported here, i'll make a note for future releases to get that addressed.
